Remove uses of ClassTemplateSpecializationDecl::getTypeAsWritten
marxin/cvise pull request #143
Opened 2024-05-29 14:01 UTC by sdkrystian

Fixes #142

2024-05-29 14:25 UTC, marxin commented
The suggested change looks fine! However, it seems the additional changes to the renaming pass will be needed in order to fix the 2 failures spotted with LLVM 19.

@sdkrystian Are you willing to work on that as part of this PR?

2024-05-29 14:59 UTC, sdkrystian commented
@marxin I pushed a commit which should fix the failing tests

2024-05-29 21:27 UTC, marxin requested changes
I think the following changes are needed for a proper compilation.

2024-05-29 21:27 UTC, marxin commented on clang_delta/RemoveNamespace.cpp
> +    TheRewriter->ReplaceText(LocStart, CXXRD->getNameAsString().size(), Name);
```suggestion
    ConsumerInstance->TheRewriter.ReplaceText(LocStart, CXXRD->getNameAsString().size(), Name);
```

2024-05-29 21:27 UTC, marxin commented on clang_delta/RemoveNamespace.cpp
> +  if (getNewName(CXXRD, Name)) {
```suggestion
  if (ConsumerInstance->getNewName(CXXRD, Name)) {
```

2024-05-30 10:47 UTC, sdkrystian commented on clang_delta/RemoveNamespace.cpp
> +    TheRewriter->ReplaceText(LocStart, CXXRD->getNameAsString().size(), Name);
Oops :P

2024-05-30 10:53 UTC, sdkrystian commented
@marxin updated

2024-05-30 11:20 UTC, marxin commented
The current LLVM master seems promising, but we will likely need a conditional build for the existing releases. What do you think 🤔?

2024-06-03 10:33 UTC, merged

2024-06-03 10:35 UTC, marxin commented
The CI should be happy after 16a34b273966e32843b3f193590198e2a769b1b0.